config/routes.rb
Rails.application.routes.draw do
  scope '(:locale)', locale: /pt-BR|en/ do
    devise_for :useres
    
    root to: "noticias#index" 

  resources :ramais do
    collection do
      get 'remove_all'
    end
  end
  resources :noticias do
      resources :comentarios, only: %i[create destroy]
    end
    resources :categorias, except: [:show]
    resources :jornais
  end

  post 'import_ramais' => "ramais#import_ramais"
  
end

app/models/comentario.rb
class Comentario < ApplicationRecord
  belongs_to :noticia
  belongs_to :user

  validates :body, presence: true
end

app/controllers/comentarios_controller.rb
class ComentariosController < ApplicationController
    before_action :authenticate_user!
    before_action :set_noticia

    def create
        @noticia.comentarios.create(comentario_params.to_h.merge!({user_id: current_user.id}))
        redirect_to noticia_path(@noticia)
    end

    def destroy
        comentario = @noticia.comentarios.find(params[:id])
        authorize comentario
    
        comentario.destroy
        redirect_to noticia_path(@noticia), notice: 'Comentário apagado com sucesso'
    end

    private

    def comentario_params
        params.require(:comentario).permit(:body)
    end

    def set_noticia
        @noticia = Noticia.find(params[:noticia_id])
    end
    
end

app/helpers/comentarios_helper.rb
module ComentariosHelper
end

app/views/comentarios/_comentario.html.erb
<div class="card mb-3">
    <div class="card-body">
    <h5 class="card-title"><%= month_day_comma_year(comentario.created_at) %></h5>
    <h6 class="card-subtitle mb-2 text-muted">Por: <%= comentario.user.first_name %> <%= comentario.user.email %></h6>
    <p class="card-text"><%= comentario.body %></p>
    <%= button_to "Apagar", noticia_comentario_path(@noticia, comentario), method: :delete, class:"btn btn-danger mb-3" if policy(@noticia).destroy? %>
</div>

app/views/comentarios/_form.html.erb
<%= simple_form_for [@noticia, @noticia.comentarios.build] do |f| %>
    <div class="form-inputs">
        <%= f.input :body, label: 'Escreva seu comentário', input_html: {rows: 10} %>
    </div>
    <div class="forma-action">
        <%= f.button :submit, class: 'btn btn-primary mb-3' %>
    </div>
<% end %>