config/routes.rb
Rails.application.routes.draw do
  scope '(:locale)', locale: /pt-BR|en/ do
    devise_for :useres
    
    root to: "noticias#index" 

  resources :ramais do
    collection do
      get 'remove_all'
    end
  end
  resources :noticias do
      resources :comentarios, only: %i[create destroy]
    end
    resources :categorias, except: [:show]
    resources :jornais
  end

  post 'import_ramais' => "ramais#import_ramais"
  
end

app/models/noticia.rb
class Noticia < ApplicationRecord

    belongs_to :categoria
    belongs_to :user

    has_many :comentarios, dependent: :destroy

    validates :titulo, presence: true, length: { minimum: 5}
    validates :content, presence: true, length: { minimum: 10}

    mount_uploader :arquivo, ArquivoUploader
    has_rich_text :content

    paginates_per 6

    scope :desc_order, -> { order(created_at: :desc)}
    scope :without_principais, -> (ids) { where("id NOT IN(#{ids})") if ids.present? }
    scope :filtro_por_categoria, -> (categoria) { where categoria_id: categoria.id if categoria.present? }
    scope :filtro_por_arquivo, lambda { |month_year|
        if month_year
            date = Date.strptime( month_year, '%B %Y' )
            where created_at: date.beginning_of_month..date.end_of_month.next_day
        end
    }
end

app/controllers/noticias_controller.rb
class NoticiasController < ApplicationController
  include Paginable

  before_action :authenticate_user!, except: %i[index show]
  before_action :set_noticia, only: %i[edit update destroy ]
  before_action :set_categorias, only: %i[new create edit update]

  # GET /noticias or /noticias.json
  def index
    @arquivos = Noticia.group_by_month(:created_at, format: '%B %Y', locale: :en).count  
    @categorias = Categoria.sorted
    categoria = @categorias.select { |c| c.name == params[:categoria] }[0] if params[:categoria].present?
    @principais = Noticia.includes(:categoria, :user, :rich_text_content)
                         .filtro_por_categoria(categoria)
                         .filtro_por_arquivo(params[:month_year])
                         .desc_order
                         .first(3)
                         
                         
    
    principal_ids = @principais.pluck(:id).join(',')

    
    
    @noticias = Noticia.includes(:categoria, :user, :rich_text_content)
                       .without_principais(principal_ids)
                       .filtro_por_categoria(categoria)
                       .filtro_por_arquivo(params[:month_year])
                       .desc_order
                       .with_rich_text_content
                       .page(current_page)
                       
             
                       
    
  end

  # GET /noticias/1 or /noticias/1.json
  def show
    @noticia = Noticia.includes(comentarios: :user).find(params[:id])
    authorize @noticia
  end

  # GET /noticias/new
  def new
    @noticia = current_user.noticias.new
  end

  # GET /noticias/1/edit
  def edit
  end

  # POST /noticias or /noticias.json
  def create
    @noticia = current_user.noticias.new(noticia_params)

    respond_to do |format|
      if @noticia.save
        format.html { redirect_to noticia_url(@noticia), notice: "Noticia criada con sucesso." }
        format.json { render :show, status: :created, location: @noticia }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @noticia.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /noticias/1 or /noticias/1.json
  def update
    respond_to do |format|
      if @noticia.update(noticia_params)
        format.html { redirect_to noticia_url(@noticia), notice: "Noticia atualizada com sucesso." }
        format.json { render :show, status: :ok, location: @noticia }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @noticia.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /noticias/1 or /noticias/1.json
  def destroy
    @noticia.destroy

    respond_to do |format|
      format.html { redirect_to noticias_url, alert: "Noticia apagada com sucesso." }
      format.json { head :no_content }
    end
  end

  private
    
    def noticia_params
      params.require(:noticia).permit(:titulo, :texto, :content, :arquivo, :categoria_id)
    end

    def set_noticia
      @noticia = Noticia.find(params[:id])
      authorize @noticia
    end

    def set_categorias
      @categorias = Categoria.sorted
    end
end

app/views/noticias/_form.html.erb
<%= simple_form_for(@noticia) do |f| %>
  <% if noticia.errors.any? %>
    <div class="alert alert-danger" role="alert">
      <h3><%= pluralize(noticia.errors.count, "erro") %> proibiu que esta noticia fosse salva:</h3>

      <ul>
        <% noticia.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <div class="form-inputs">
      <%= f.input :titulo, label: "Título" %>
      <%= f.input :content, as: :rich_text_area, label: 'Texto', placeholder: 'Insira seu texto aqui' %>
      <%= f.association :categoria, collection: @categorias, prompt: "Escolha uma categoria" %>
      <%= f.file_field :arquivo, class:"form-control" %>
    </div>


    <div class="form-action">
      <%= f.button :submit, class: 'btn btn-outline-success mb-3' %>
    </div>
  </div>
<% end %>

app/views/noticias/_noticia.html.erb
<div id="<%= dom_id noticia %>">
  <article class="blog-post">
    <strong class="d-inline-block mb-2 text-primary h6"><%= render '/noticias/layoutsBlog/noticia_categoria', noticia: noticia %></strong>
    <h2 class="blog-post-title mb-1 border-bottom"><%= noticia.titulo %></h2>
    <p class="mb-2 text-muted"><%= render '/noticias/layoutsBlog/noticia_data', noticia: noticia %></p>
    <figure class="figure float-end mb-0">
      <%= image_tag (noticia.arquivo_url), :class => "figure-img img-fluid rounded mb-0", :width => "400" %>
    </figure>
    <section>
      <p><%= noticia.content %></p>
    </section>
    <p>
      

    </p>
      
  </article>
</div>

      

app/views/noticias/edit.html.erb
  <div class="row align-items-center mt-5">
      <div class="col-3">
      
      </div>
      <div class="col-6">
        <h1>Editar Notícia</h1>
      </div>
      <div class="col-3">
      
      </div>
  </div>
  <%= render "form", noticia: @noticia %>

  <br>

    <%= link_to "Voltar", noticias_path, class:"btn btn-outline-success mb-3" %>
    <%= link_to "Mostrar", @noticia, class:"btn btn-outline-primary mb-3" %>
    <%= button_to "Apagar", @noticia, method: :delete, class:"btn btn-outline-danger mb-3" if policy(@noticia).update? %>
  </div>

app/views/noticias/index.html.erb
  
  <%= render_if @principais[0].present?, '/noticias/layoutsBlog/principalBlog', noticia: @principais[0] %>
  <div class="row mb-2">
    <%= render_if @principais[1].present?, '/noticias/layoutsBlog/principaisBlogs', noticia: @principais[1] %>
    <%= render_if @principais[2].present?, '/noticias/layoutsBlog/principaisBlogs', noticia: @principais[2] %>
  </div>

  <div class="row g-5">
    <div class="col-md-8">
      <h3 class="pb-4 mb-4 fst-italic border-bottom">
        Notícias
      </h3>
      <p>
        <% if current_user && current_user.admin? %>
          <%= link_to 'Nova Notícia', new_noticia_path, class: "btn btn-outline-success" if user_signed_in? %>
        <% end %>
      </p>

      <% @noticias.each do |noticia| %>
        <div class="col-md-12">
            <div class="row g-0 border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-300 position-relative">
              <div class="col p-4 d-flex flex-column position-static">
                  <strong class="d-inline-block mb-2 text-primary h6"><%= render '/noticias/layoutsBlog/noticia_categoria', noticia: noticia %></strong>
                  <h4 class="mb-0"><%= noticia.titulo %></h4>
                  <div class="mb-1 text-muted"><small><%= render '/noticias/layoutsBlog/noticia_data', noticia: noticia %></small></div>
                  <p class="card-text mb-auto"><small><%= noticia.content.to_plain_text.truncate(150) %></small></p>
                  <p class="mb-4">
                    <small><%= link_to "Continue lendo ...", noticia, class:"stretched-link" %></small>
                  </p>
                  <div>
                    <!--<%= link_to "Editar", edit_noticia_path(noticia), class:"btn btn-outline-primary mb-3" if policy(noticia).update? %>
                    <%= link_to "Apagar", @noticia, method: :delete, data: { confirm: 'Você tem certeza?' }, class:"btn btn-outline-danger mb-3" if policy(noticia).destroy? %>-->
                  </div>
              </div>
              <div class="col-auto d-none d-lg-block">
                  <%= image_tag noticia.arquivo_url, :class => "bd-placeholder-img", :width => "250", :height => "320" if noticia.arquivo.present?  %>
              </div>
            </div>
        </div>
        
      <% end %>

      <nav class="blog-pagination" aria-label="Pagination">
        <%= link_to_next_page @noticias, 'Anterior', class: "btn btn-outline-primary mb-3" %>
        <%= link_to_previous_page @noticias, 'Próximo', class: "btn btn-outline-secondary mb-3" %>
      </nav>

    </div>
    <%= render :partial => '/noticias/layoutsBlog/sideBlog' %>
  </div>

app/views/noticias/new.html.erb
  <div class="row align-items-center mt-5">
      <div class="col-3">
        
      </div>
      <div class="col-6">
        <h1>Nova Notícia</h1>
      </div>
      <div class="col-3">
      
      </div>
  </div>
  <%= link_to 'Categorias', categorias_path, class: "btn btn-outline-primary mb-3" %>
  <%= render "form", noticia: @noticia %>

  <br>

    <%= link_to "Voltar", noticias_path, class:"btn btn-outline-success mb-3" %>
  </div>

app/views/noticias/show.html.erb
 
  <div class="row g-5 mb-5">
    <div class="col-md-12">
      <h3 class="pb-4 mb-4 fst-italic">
        
      </h3>

      <%= render @noticia %>
      <% if current_user && current_user.admin? %>
        <div class="mb-4">
          <%= link_to "Editar", edit_noticia_path(@noticia), class:"btn btn-outline-primary mb-3" if policy(@noticia).update? %>
          <%= link_to "Voltar", noticias_path, class:"btn btn-outline-success mb-3" %>
        </div>
        <div class="mb-4">
          <%= button_to "Apagar", @noticia, method: :delete, class:"btn btn-outline-danger mb-3" if policy(@noticia).destroy? %>
        </div>
      <% end %>


      <h2 class="mt-3">Comentários</h2>
      <%= render @noticia.comentarios %>


      <h2>Adicione um comentário:</h2>
      <% if policy(:comentario).create? %>
        <%= render 'comentarios/form' %>
      <% else %>
        <p>Por favor, faça login para criar um comentário.</p>
      <% end %>


      <!--<nav class="blog-pagination" aria-label="Pagination">
        <a class="btn btn-outline-primary rounded-pill" href="#">Older</a>
        <a class="btn btn-outline-secondary disabled">Newer</a>
      </nav>-->

    </div>
  </div>