config/routes.rb
Rails.application.routes.draw do
  scope '(:locale)', locale: /pt-BR|en/ do
    devise_for :useres
    
    root to: "noticias#index" 

  resources :ramais do
    collection do
      get 'remove_all'
    end
  end
  resources :noticias do
      resources :comentarios, only: %i[create destroy]
    end
    resources :categorias, except: [:show]
    resources :jornais
  end

  post 'import_ramais' => "ramais#import_ramais"
  
end

app/controllers/ramais_controller.rb
class RamaisController < ApplicationController
  before_action :authenticate_user!, except: %i[index show]
  before_action :set_ramal, only: %i[ show edit update destroy ]

  # GET /ramais or /ramais.json
  def index
    @ramais = Ramal.all
  end

  # GET /ramais/1 or /ramais/1.json
  def show
  end

  def remove_all
    Ramal.delete_all
    flash[:notice] = "Lista removida com sucesso"
    redirect_to new_ramal_path
  end

  def import_ramais
    file = params[:file]
    begin
      file_ext = File.extname(file.original_filename)
      raise "Unknown file type: #{file.original_filename}" unless [".xls", ".xlsx"].include?(file_ext)
      spreadsheet = (file_ext == ".xls") ? Roo::Excel.new(file.path) : Roo::Excelx.new(file.path)
      header = spreadsheet.row(1)
      ## We are iterating from row 2 because we have left row one for header
      (2..spreadsheet.last_row).each do |i|
        @ramal = current_user.ramais.create(setor: spreadsheet.row(i)[0], telefone: spreadsheet.row(i)[1], email: spreadsheet.row(i)[2], departamento: spreadsheet.row(i)[3])
      end
      flash[:notice] = "Lista importada"
      redirect_to ramais_path 
    rescue Exception => e
      flash[:alert] = "Problemas com o arquivo"
      redirect_to ramais_path 
    end
 end

  # GET /ramais/new
  def new
    @ramal = current_user.ramais.new
  end

  # GET /ramais/1/edit
  def edit
  end

  # POST /ramais or /ramais.json
  def create
    @ramal = current_user.ramais.new(ramal_params)

    respond_to do |format|
      if @ramal.save
        format.html { redirect_to ramal_url(@ramal), notice: "Ramal criado com sucesso." }
        format.json { render :show, status: :created, location: @ramal }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @ramal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ramais/1 or /ramais/1.json
  def update
    respond_to do |format|
      if @ramal.update(ramal_params)
        format.html { redirect_to ramal_url(@ramal), notice: "Ramal atualizado com sucesso." }
        format.json { render :show, status: :ok, location: @ramal }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @ramal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ramais/1 or /ramais/1.json
  def destroy
    @ramal.destroy

    respond_to do |format|
      format.html { redirect_to ramais_url, notice: "Ramal apagado com sucesso." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ramal
      @ramal = Ramal.find(params[:id])
      authorize @ramal
    end

    # Only allow a list of trusted parameters through.
    def ramal_params
      params.require(:ramal).permit(:setor, :telefone, :email, :departamento)
    end
end

app/helpers/ramais_helper.rb
module RamaisHelper
end

app/views/ramais/_form.html.erb
<%= simple_form_for(@ramal) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :setor %>
    <%= f.input :telefone %>
    <%= f.input :email %>
    <%= f.input :departamento %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, 'Salvar', class: 'btn btn-outline-success mb-3' %>
  </div>
<% end %>

app/views/ramais/_ramal.html.erb
<div id="<%= dom_id ramal %>">

  <table class="table mb-5">
    <thead>
      <tr class="table-primary">
        <th scope="col">Setor:</th>
        <th scope="col">Telefone:</th>
        <th scope="col">Email:</th>
        <th scope="col">Departamento:</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td><%= ramal.setor %></td>
        <td><%= ramal.telefone %></td>
        <td><%= ramal.email %></td>
        <td><%= ramal.departamento %></td>
      </tr>
    </tbody>
  </table>
    

</div>

app/views/ramais/edit.html.erb
<div class="row align-items-center mt-5">
    <div class="col-3">
      
    </div>
    <div class="col-6">
      <h1 class="text-primary">Editar Ramal</h1>
    </div>
    <div class="col-3">
    
    </div>
</div>

<%= render "form", ramal: @ramal %>

<br>

<div>
  <%= link_to "Mostrar", @ramal, class:"btn btn-outline-primary mb-3" %>
  <%= link_to "", ramais_path, class:"mb-3 bi bi-box-arrow-left btn btn-outline-success mb-3" %>
  <%= button_to "Apagar", @ramal, method: :delete, class:"btn bi bi-trash3 btn-danger mb-3"  if policy(@ramal).destroy? %>
</div>

app/views/ramais/index.html.erb
<div class="row align-items-center mt-3">
      <div class="col-3">
        
      </div>
      <div class="col-6">
        <h1 class="text-primary">Ramais</h1>
      </div>
      <div class="col-3">
      
      </div>
  </div>
  <% if current_user && current_user.admin? %>
    <%= link_to "Novo Ramal", new_ramal_path, class:"btn btn-outline-primary" if user_signed_in? %>
  <% end %>

  <table id="table" data-toggle="table" data-search="true" data-show-columns="true" class="table">
  <thead>
    <tr class="tr-class-1">
      <th scope="col" data-field="setor" data-valign="middle"><strong>Setor</strong></th>
      <th scope="col" data-field="telefone" data-valign="middle"><strong>Número</strong></th>
      <th scope="col" data-field="email" data-valign="middle"><strong>Email</strong></th>
      <th scope="col" data-field="departamento" data-valign="middle"><strong>Departamento</strong></th>
      <th scope="col" data-field="mostrar" data-valign="middle"><strong></strong></th>
      <%  if current_user && current_user.admin? %>
        <th scope="col" data-field="editar" data-valign="middle"><strong></strong></th>
        <th scope="col" data-field="apagar" data-valign="middle"><strong></strong></th>
      <% end %>
    </tr>
  </thead>
  <tbody class="table-group-divider">
    <% @ramais.each do |ramal| %>
      <tr>
        <th><%= ramal.setor %></th>
        <th class="col-1 text-center"><%= ramal.telefone %></th>
        <th><%= ramal.email %></th>
        <th><%= ramal.departamento %></th>
        <th><%= link_to "", ramal, class: "btn btn-primary bi bi-box-arrow-right mb-3" %></th>
        <%  if current_user && current_user.admin? %>
          <th><%= link_to "", edit_ramal_path(ramal), class:"btn btn-secondary mb-3 bi bi-pencil-square" if user_signed_in? %></th>
          <th><%= button_to "", ramal, method: :delete, class:"btn btn-danger mb-3 bi bi-trash3 mb-3" if user_signed_in? %></th>
        <% end %>
        
      </tr>
    <% end %>
  </tbody>
</table>
  

app/views/ramais/new.html.erb
  <div class="row align-items-center mt-3 mb-3">
    <div class="col-3">
        
      </div>
      <div class="col-6">
        <h1 class="text-primary">Nova Lista de Ramais</h1>
      </div>
      <div class="col-3">
      
      </div>
    <div class="row align-items-center mt-5 mb-5">
      <div class="col-6">
      <h3 class="text-primary">Apagar lista de Ramais</h3>
      <p class="text-secondary"></p>
        <%= link_to "Apagar Ramais", remove_all_ramais_path, :method => :get, class: "btn btn-danger mb-3" %>
      </div>
      <div class="col-6">
        <h3 class="text-primary">Importar Ramais</h3>
        <p class="text-secondary"></p>
        <%= form_tag import_ramais_path, multipart: true do %>
          <span class="btn btn-large btn-secondary btn-file mb-3">
            Escolha uma arquivo
            <%= file_field_tag :file %>
          </span>
          <%= submit_tag "Importar", :class=> "btn btn-primary mb-3 ms-3" %>
        <% end %>
      </div>
    </div>
  <div>



<%= render "form", ramal: @ramal %>

<br>

<div>
  <%= link_to " Voltar", ramais_path, class: "btn btn-primary bi bi-box-arrow-left mb-3"  %>
</div>

app/views/ramais/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @ramal %>

<div>
  <%= link_to "Editar", edit_ramal_path(@ramal), class:"btn btn-outline-primary mb-3" if policy(@ramal).update? %>
  <%= link_to "Voltar", ramais_path, class:"btn btn-outline-success mb-3" %>
  <%= button_to "", @ramal, method: :delete, class:"btn btn-danger mb-3 bi-trash3 mb-3" if policy(@ramal).update? %>
</div>