config/routes.rb
Rails.application.routes.draw do
  scope '(:locale)', locale: /pt-BR|en/ do
    devise_for :useres
    
    root to: "noticias#index" 

  resources :ramais do
    collection do
      get 'remove_all'
    end
  end
  resources :noticias do
      resources :comentarios, only: %i[create destroy]
    end
    resources :categorias, except: [:show]
    resources :jornais
  end

  post 'import_ramais' => "ramais#import_ramais"
  
end

app/views/layouts/_caroussel.html.erb
<script type="text/javascript">
      document.addEventListener("DOMContentLoaded", function(){
        
        window.addEventListener('scroll', function() {
            
          if (window.scrollY > 500) {
            document.getElementById('navbar_top').classList.add('fixed-top');
            // add padding top to show content behind navbar
            navbar_height = document.querySelector('.navbar').offsetHeight;
            document.body.style.paddingTop = navbar_height + 'px';
          } else {
            document.getElementById('navbar_top').classList.remove('fixed-top');
            // remove padding top from body
            document.body.style.paddingTop = '0';
          } 
        });
      }); 
      // DOMContentLoaded  end
    </script>

    <style type="text/css">
      .fixed-top {
          top: -40px;
          transform: translateY(40px);
          transition: transform .3s;
      }

    </style>
    <div id="myCarousel" class="carousel slide carousel-fade" data-bs-ride="carousel">
    <div class="carousel-indicators">
      <button type="button" data-bs-target="#myCarousel" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
      <button type="button" data-bs-target="#myCarousel" data-bs-slide-to="1" aria-label="Slide 2"></button>
      <button type="button" data-bs-target="#myCarousel" data-bs-slide-to="2" aria-label="Slide 3"></button>
      <button type="button" data-bs-target="#myCarousel" data-bs-slide-to="3" aria-label="Slide 3"></button>
      <button type="button" data-bs-target="#myCarousel" data-bs-slide-to="4" aria-label="Slide 3"></button>
    </div>
    <div class="carousel-inner">
      <div class="carousel-item active" data-bs-interval="5000">
        <%= image_tag "caroussel/team-of-doctor-1.jpg", :class => "w-100" %>
        <div class="container">
          <div class="carousel-caption text-start">
          <h1>Estreia da nova intranet HEGV!</h1>
          <p class="h6">Navegação se torna mais simples com a chegada do novo sistema.</p>
          <p><a class="btn btn-lg btn-primary" href="#">Saiba mais</a></p>
          </div>
        </div>
      </div>
      <div class="carousel-item" data-bs-interval="5000">
      <%= image_tag "caroussel/team-of-doctor-2.jpg", :class => "w-100" %>
        <div class="container">
          <div class="carousel-caption">
            <h1>Facilidades</h1>
            <p class="h6">Aqui você encontrará o necessário para o seu bom desenvolvimento de trabalho.</p>
            <p><a class="btn btn-lg btn-primary" href="#">Saiba mais</a></p>
          </div>
        </div>
      </div>
      <div class="carousel-item" data-bs-interval="5000">
      <%= image_tag "caroussel/team-of-doctor-3.jpg", :class => "w-100" %>
        <div class="container">
          <div class="carousel-caption text-end">
          <h1>Novidades, Notícias e Eventos</h1>
          <p class="h6">Fique atualizado com nossos informes.</p>
          <p><a class="btn btn-lg btn-primary" href="#">Saiba mais</a></p>
          </div>
        </div>
      </div>
      <div class="carousel-item" data-bs-interval="5000">
      <%= image_tag "caroussel/team-of-doctor-4.jpg", :class => "w-100" %>
        <div class="container">
          <div class="carousel-caption text-end">
          <h1>Estreia da nova intranet HEGV!</h1>
          <p class="h6">Navegação se torna mais simples com a chegada do novo sistema.</p>
          <p><a class="btn btn-lg btn-primary" href="#">Saiba mais</a></p>
          </div>
        </div>
      </div>
      <div class="carousel-item" data-bs-interval="5000">
      <%= image_tag "caroussel/team-of-doctor-5.jpg", :class => "w-100" %>
        <div class="container">
          <div class="carousel-caption text-end">
          <h1>Estreia da nova intranet HEGV!</h1>
          <p class="h6">Navegação se torna mais simples com a chegada do novo sistema.</p>
          <p><a class="btn btn-lg btn-primary" href="#">Saiba mais</a></p>
          .</div>
        </div>
      </div>
    </div>
    
  </div>

app/views/layouts/_contas_usuarios_links.html.erb
<% if user_signed_in? %>
    <div class="dropdown">
        <button class="btn btn-primary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
            <%= current_user.first_name %> <%= current_user.last_name %>
        </button>
        <ul class="dropdown-menu">
            <li>
                <%= link_to 'Editar usuário', edit_user_registration_path, class: 'dropdown-item' %>
            </li>
            <li><hr class="dropdown-divider"></li>
            <li>
                <%= link_to 'Sair', destroy_user_session_path, method: :delete, class: 'dropdown-item' %>
            </li>
        </ul>
    </div>
<% else %>
    <%= link_to 'Entrar', new_user_session_path, class:" py-2 mb-2 btn btn-outline-primary rounded-3" %>&nbsp;&nbsp;
    <!--<%= link_to 'Resgitre-se', new_user_registration_path, class:" py-2 mb-2 btn btn-outline-primary rounded-3" %>-->
<% end %>

app/views/layouts/_flash_messages.html.erb
<div class="row mb-2 mt-4">
    <% if notice.present? %>
        <div class="alert alert-success alert-dismissible fade show" role="alert">
            <%= notice %>
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
    <% end %>
    <% if alert.present? %>
        <div class="alert alert-danger alert-dismissible fade show" role="alert">
            <%= alert %>
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
    <% end %>
</div>

app/views/layouts/_footer.html.erb
<!-- Footer -->
<footer class="text-center text-lg-start text-muted" style="background-color: #045B9336;">
  <!-- Section: Social media 
  <section class="d-flex justify-content-center justify-content-lg-between p-4 border-bottom">
    
    <div class="me-5 d-none d-lg-block">
      <span>Conecte-se em nossas redes sociais:</span>
    </div>
    

    
    <div>
      <a href="" class="me-4 link-secondary">
        <i class="bi bi-facebook"></i>
      </a>
      <a href="" class="me-4 link-secondary">
        <i class="bi bi-twitter"></i>
      </a>
      <a href="" class="me-4 link-secondary">
        <i class="bi bi-google"></i>
      </a>
      <a href="" class="me-4 link-secondary">
        <i class="bi bi-instagram"></i>
      </a>
      <a href="" class="me-4 link-secondary">
        <i class="bi bi-linkedin"></i>
      </a>
    </div>
    
  </section>
  Section: Social media -->

  <!-- Section: Links  -->
  <section class="d-flex p-4">
    <div class="container text-center text-md-start mt-5">
      <!-- Grid row -->
      <div class="row mt-3">
        <!-- Grid column -->
        <div class="col-md-4 col-lg-4 col-xl-4 mx-auto mb-4">
          <!-- Content -->
          <h6 class="text-uppercase fw-bold mb-4">
            Hospital Estadual Getúlio Vargas
          </h6>
          <p>
            <a href="#!" class="text-reset text-decoration-none">Home</a>
          </p>
          <p>
            <a href="#!" class="text-reset text-decoration-none">Campus Virtual</a>
          </p>
        </div>
        <!-- Grid column -->

        <!-- Grid column -->
        <div class="col-md-4 col-lg-4 col-xl-4 mx-auto mb-4">
          <!-- Links -->
          <h6 class="text-uppercase fw-bold mb-4">
            Manuais e Procedimentos
          </h6>
          <p>
            <a href="#!" class="text-reset text-decoration-none">POPs</a>
          </p>
          <p>
            <a href="#!" class="text-reset text-decoration-none">Lista de Presença</a>
          </p>
          <p>
            <a href="#!" class="text-reset text-decoration-none">Formulário de bancada</a>
          </p>
          <p>
            <a href="#!" class="text-reset text-decoration-none">Solicitação de acesso</a>
          </p>
          <p>
            <a href="#!" class="text-reset text-decoration-none">Ocorrência de ponto</a>
          </p>
          <p>
            <a href="#!" class="text-reset text-decoration-none">Troca de plantão</a>
          </p>
        </div>
        <!-- Grid column -->

        <!-- Grid column -->
        <div class="col-md-3 col-lg-2 col-xl-2 mx-auto mb-4">
          <!-- Links -->
          <h6 class="text-uppercase fw-bold mb-4">
            Links Úteis
          </h6>
          <p>
            <a href="#!" class="text-reset text-decoration-none">TI Med - HEGV</a>
          </p>
          <p>
            <a href="#!" class="text-reset text-decoration-none">TI Med - UPA</a>
          </p>
          <p>
            <a href="#!" class="text-reset text-decoration-none">Bios Lab</a>
          </p>
          <p>
            <a href="#!" class="text-reset text-decoration-none">GLPI - Central de Soluções</a>
          </p>
          <p>
            <a href="#!" class="text-reset text-decoration-none">Zamed - Logística</a>
          </p>
          <p>
            <a href="#!" class="text-reset text-decoration-none">CadWeb</a>
          </p>
          <p>
            <a href="#!" class="text-reset text-decoration-none">Lista de Ramais</a>
          </p>
          <p>
            <a href="#!" class="text-reset text-decoration-none">Dúvidas Frequentes</a>
          </p>
        </div>
        <!-- Grid column -->

        
      </div>
      <!-- Grid row -->
    </div>
  </section>
  <!-- Section: Links  -->

  <!-- Copyright -->
  <div class="text-center p-4" style="background-color: rgba(0, 0, 0, 0.025);">
    © 2022 Copyright:
    <a class="text-reset fw-bold" href="http://intranet.cesp">Equipe de T.I. Hospital Estadual Getúlio Vargas</a>
  </div>
  <!-- Copyright -->
</footer>
<!-- Footer -->

app/views/layouts/_header.html.erb
<%= render '/layouts/caroussel' %>

<!-- ============= COMPONENT ============== -->
<nav id="navbar_top" class="navbar navbar-expand-lg navbar-dark" style="background-color: #045B93;">
 <div class="container">
 	<%= link_to root_path do %>
        <%= image_tag "logos/logo_hegv_background_none.png", :class => "mx-1" %>
    <% end %> 
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#main_nav"  aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
  <div class="collapse navbar-collapse justify-content-center" id="main_nav">
	

	<ul class="navbar-nav">
        <li class="nav-item">
        <%= link_to "Home", root_path, class: "nav-link active" %>
        </li>
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="manuaisProcedimentos" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Manuais e Procedimentos
            </a>
            <ul class="dropdown-menu" aria-labelledby="manuaisProcedimentos">
            <li><a class="dropdown-item" href="#">POP's</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><%= link_to "Lista de Presença", "assets/documents/nep_lista_de_presenca.pdf", target:"_blank", class:"dropdown-item" %></li>
            <li><%= link_to "Formulário de Solicitação de acesso", "assets/documents/ti_solicitacao_de_acesso.pdf", target:"_blank", class:"dropdown-item" %></li>
            <li><%= link_to "Ocorrência de Ponto", "assets/documents/dp_ocorrencia_de_ponto.pdf", target:"_blank", class:"dropdown-item" %></li>
            <li><%= link_to "Formulário de Troca de Plantão", "assets/documents/dp_solicitacao_de_troca_de_plantao.pdf", target:"_blank", class:"dropdown-item" %></li>
            </ul>
        </li>
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="comunicaoesEventos" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Comunicação e Eventos
            </a>
            <ul class="dropdown-menu" aria-labelledby="comunicaoesEventos">
            <li><%= link_to "Notícias", noticias_path, class:"dropdown-item" %></li>
            <li><%= link_to "Jornal CESP News", jornais_path, class:"dropdown-item" %></li>
            <li><a class="dropdown-item" href="#">Eventos</a></li>
            </ul>
        </li>
        <li class="nav-item">
            <%= link_to "Campus Virtual", "http://10.42.68.6/", target:"_blank", class:"nav-link" %> 
        </li>
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="linksUteis" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Links Úteis
            </a>
            <ul class="dropdown-menu" aria-labelledby="linksUteis">
            <li><small><%= link_to "TI Med - HEGV", "http://10.42.69.4:8080/vitai/pages/login.do", target:"_blank", class:"dropdown-item" %></small></li>
            <li><small><%= link_to "TI Med - UPA", "http://10.42.169.5:8080/vitai/pages/login.do", target:"_blank", class:"dropdown-item" %></small></li>
            <li><small><%= link_to "LisNet", "https://ultraimagem.lisnet.com.br/laudos/#u", target:"_blank", class:"dropdown-item" %></small></li>
            <li><small><%= link_to "GLPI - Central de Soluções", "http://centraldesolucoes.cesp/glpi/", target:"_blank", class:"dropdown-item" %></small></li>
            <li><small><%= link_to "Zamed - Logística", "https://ipcep.zamedsaude.com.br/", target:"_blank", class:"dropdown-item" %></small></li>
            <li><small><%= link_to "CadWeb", "https://cadastro.saude.gov.br/segcartao/?contextType=external&username=string&contextValue=%2Foam&password=sercure_string&challenge_url=https%3A%2F%2Fcadastro.saude.gov.br%2Fsegcartao&request_id=-690881192035479294&authn_try_count=0&locale=pt_BR&resource_url=http%253A%252F%252Fcadastro.saude.gov.br%252Fnovocartao%252Frestrito%252FusuarioConsulta.jsp", target:"_blank", class:"dropdown-item" %></small></li>
            <li><small><%= link_to "Exames de Imagem", "https://laudos.mobilemed.com.br/login", target:"_blank", class:"dropdown-item" %></small></li>
            <li><small><%= link_to "Ramais", ramais_path, class:"dropdown-item" %></small></li>
            <li><small><%= link_to "Painel de Indicadores", "http://10.42.68.19/", target:"_blank", class:"dropdown-item" %></small></li>
            </ul>
        </li>
    </ul>

  </div> <!-- navbar-collapse.// -->
  <%= render 'layouts/contas_usuarios_links' %>
 </div> <!-- container-fluid.// -->
 
    
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="pt-BR">
  <head>
    <meta charset="utf-8">
    <title>HEGV - CESP</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <link rel="stylesheet" href="https://unpkg.com/bootstrap-table@1.21.1/dist/bootstrap-table.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.2/font/bootstrap-icons.css">
    
    <link href="https://fonts.googleapis.com/css?family=Playfair&#43;Display:700,900&amp;display=swap" rel="stylesheet">
  </head>

  <body>
      <%= render '/layouts/header' %>
      <main class="container">
        <%= render '/layouts/flash_messages' %>
        <%= yield %>
      </main>
      <%= render '/layouts/footer' %>
      
<script src="https://cdn.jsdelivr.net/npm/jquery/dist/jquery.min.js"></script>
<script src="https://unpkg.com/bootstrap-table@1.21.1/dist/bootstrap-table.min.js"></script>
  </body>
</html>